### ISSUE TITLE
ONIMP Auto Installer

### ISSUE THREAD

**Issue by Antonio0447** [zuev93/oni_multiplayer#102]
https://github.com/Antonio0447/ONIMultiplayer_Installer a ONIMP auto installer/updater.

**Comment by zuev93** [comment]
Hi @Antonio0447 ,
Thanks for doing this!

I've a question: how do you suggest to use your installer?

**Comment by Antonio0447** [comment]
> Hi @Antonio0447 , Thanks for doing this!
> 
> I've a question: how do you suggest to use your installer?

Im not sure what you mean by that but My installer has an auto installer that installs everything automatically no need to download the files manually everything is automatic including updates it auto updates so if you open it anytime it will delete the old installation and download a new updated installation(it will download the latest branch from your GitHub). At the moment I am rewriting everything and adding more functions to provide a better experience thank you.

**Comment by Antonio0447** [comment]
> Also this overlaps with #87

Yes, I know but the batch file is not that good its a manual installation well if you have OneDrive on your pc and it installs the MultiplayerMod inside the non-OneDrive folder it won't work you'll have to install it manually(this happened to me) I'm not doing it because of that but because I have a lot of time in my hands and well I just like coding stuff in c#.

**Comment by Ceron257** [comment]
I was just about to suggest registry keys or even native WinAPI because I saw you kind of figured out the path yourself and then saw that there's also `Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)`. Have you considered to use that?

**Comment by Antonio0447** [comment]
> I was just about to suggest registry keys or even native WinAPI because I saw you kind of figured out the path yourself and then saw that there's also `@Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)`. Have you considered to use that? 

Thank you for the suggestion I'll consider using @Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) but I’m not sure because with the rewritten code that I’m working on is different but if it does not work ill use it thanks.

**Comment by Antonio0447** [comment]
Ok, the update is now finished it's fully functional rewritten, and has better error handling.

**Comment by bielbi6** [comment]
for me have virus this new "Auto Installer"

**Comment by Antonio0447** [comment]
> for me have virus this new "Auto Installer"

Virus? No. It’s 100% safe you can view the source code.

**Comment by bielbi6** [comment]
bizzard becouse i install i think my pc don't work i try agian go

**Comment by bielbi6** [comment]
my pc says have trojan

**Comment by bielbi6** [comment]
i think is your mod

**Comment by Antonio0447** [comment]
> my pc says have trojan

Send me a screenshot of it saying and showing the ONIMultiplayer_installer.exe

**Comment by Antonio0447** [comment]
> i think is your mod

There’s no way

**Comment by bielbi6** [comment]
ok i send with discord the screenshot

**Comment by bielbi6** [comment]
if you want see my profile with discord "bielbi12"

**Comment by bielbi6** [comment]
![Captura de Tela (19)](https://github.com/zuev93/oni_multiplayer/assets/112406423/76b3ce48-d44a-454a-9fe6-9f08bb0020d1)

**Comment by Antonio0447** [comment]
> ![Captura de Tela (19)](https://github.com/zuev93/oni_multiplayer/assets/112406423/76b3ce48-d44a-454a-9fe6-9f08bb0020d1)
> 
> 

That’s not my installer that has something to do with your opera browser

**Comment by bielbi6** [comment]
dude don't work without with opera

**Comment by Antonio0447** [comment]
> dude don't work without with opera

Download with Google chrome
