### ISSUE TITLE
Can not install mod

### ISSUE THREAD

**Issue by White-Reaper1** [zuev93/oni_multiplayer#114]
@zuev93 @zuev93 @Bromvlieg I downloaded the files and everything seems to be working fine for me, but then my friend downloaded them and they are in the exact same places as me, yet they dont show the mod in game. I am running windows 10 and he is on windows 11 and that is the only difference that I have been able to figure out. I was wondering if maybe the mod is having an issue running on windows 11 or if there was someway that I could fix this issue myself.

**Comment by Antonio0447** [comment]
> @zuev93 @zuev93 @Bromvlieg I downloaded the files and everything seems to be working fine for me, but then my friend downloaded them and they are in the exact same places as me, yet they dont show the mod in game. I am running windows 10 and he is on windows 11 and that is the only difference that I have been able to figure out. I was wondering if maybe the mod is having an issue running on windows 11 or if there was someway that I could fix this issue myself.

You can use this tool https://github.com/Antonio0447/ONIMultiplayer_Installer or you can download it manually by placing it in the onedrive directory.

**Comment by zuev93** [comment]
@White-Reaper1 so far there is only one common problem around installation:
You should locate correct mod folders in documents/one drive folder.
There are 2 ways to find correct folder from the game if you are struggling to find it manually:

1. Go to game mods section (if you have any installed) and click `Browse` button. It'll bring you close to folder that you need
2. Go to game load menu. Click gear icon -> `Local saves`. It'll bring you close to folder that you need

In both cases you would need to do several steps up in folder tree until you see mods directory and after follow usual install guide (create Local/MultiplayerMod/{modfiles})

Hope it helps.
