### ISSUE TITLE
Hacker keeps joining game

### ISSUE THREAD

**Issue by White-Reaper1** [zuev93/oni_multiplayer#116]
@zuev93 @polycone @Bromvlieg Someone keeps joining my game somehow without being on my friends list and they are deleting my entire colony so that it immediately makes me restart. How in the world do i fix that

**Comment by zuev93** [comment]
Hi @White-Reaper1 sounds very strange since we are using SteamWorks API with Friends only mode.

Could you send you player.log file to help us here?

**Comment by White-Reaper1** [comment]
After I go to work I will find the file. When I looked on steam it said no recent players. My friend and I got a friend request from someone that was in the discord server though. I dont remember the name but I know that they started to message my friend azaire in one of the chats right after someone random person joined our game and just wiped our board.

**Comment by bielbi6** [comment]
sorry man i have autism i had a nervous breakdown because i wanted to play with someone when i get unstructured i do things that i regret later i could not even write this but i am very sad about what i did i promise never to do that again i just wanted to play with someone

**Comment by bielbi6** [comment]
sorry man i have autism i had a nervous breakdown because i wanted to play with someone when i get unstructured i do things that i regret later i could not even write this but i am very sad about what i did i promise never to do that again i just wanted to play with someone

**Comment by White-Reaper1** [comment]
well theres your answer lmao. its alright since you appologized and promised not to do it again, but like its not cool to join someones game uninvited as well as without even being on our friendslist. I dont know how you did it but please refrain from doing that again in the future. its only going to upset others
