### ISSUE TITLE
Sync utility (pipes/wires/vents) connections

### ISSUE THREAD

**Issue by zuev93** [zuev93/oni_multiplayer#18]
Construction of items in cells already synced, but they do not form the same conduite as has been created by the user. They just place bunch of individual peaces.

Expected behaviour:
conduite looks the same as on the other client side.

**Comment by tinetik** [comment]
Using release 0.0.3 with 2 players, and only the host seems to be able to place wires.

> Construction of items in cells already synced, but they do not form the same conduite as has been created by the user. They just place bunch of individual peaces.

Is this expected? Is there a newer version with the above behavior?

**Comment by skrilax91** [comment]
+1
Actually only the host can place wire, il dont Knowles about the rest

**Comment by zuev93** [comment]
> Is this expected? Is there a newer version with the above behavior?

Not yet, however as you can see we are aware of the issue and will fix it at some point.
When the fix will be implemented and available this ticket will be marked as resolved.

**Comment by tinetik** [comment]
> Not yet, however as you can see we are aware of the issue and will fix it at some point. When the fix will be implemented and available this ticket will be marked as resolved.

Sorry, I guess i'm confused.
The wording of the ticket makes it seems like wires are able to be placed, and just don't connect, which is not the functionality I was seeing.
