### ISSUE TITLE
Host player construct menu bug

### ISSUE THREAD

**Issue by skrilax91** [zuev93/oni_multiplayer#33]
When I click on an object to construct as a host, the menu bug and I can't place this object, the game also slow and unsync game cycle.

screenshot : 
![image](https://user-images.githubusercontent.com/6585219/228364373-f634e974-6037-4713-96e4-874f63ae813a.png)

**Comment by skrilax91** [comment]
the client don't have this issue

**Comment by tinetik** [comment]
+1 
The game goes nearly unresponsive upon opening the build menu.
Client does have the same visual bug as above, but can build as normal with no unresponsiveness.

**Comment by Terryxtl** [comment]
having the same issue:(
