### ISSUE TITLE
Constat decyncs

### ISSUE THREAD

**Issue by MrLinusK** [zuev93/oni_multiplayer#62]
Im not sure if its a problem on our side, but it constantly decyncs and makes him have to rejoin every 3min to resync the game.

**Comment by zuev93** [comment]
Hi [MrLinusK](https://github.com/MrLinusK),

Thanks for the issue.
But it is known issue and mod is still in active development stage.
Please check https://github.com/zuev93/oni_multiplayer/milestones to track the progress. As you might see we are not even in alpha stage yet. 

So please be patient and wait for further release :)
