### ISSUE TITLE
Autosave complains about not enough drive space, requesting 15MB

### ISSUE THREAD

**Issue by Iridum-png** [zuev93/oni_multiplayer#68]
Game crashes for host and client on autosave and also crashes for host whenever client performs an action (digging, cancelling orders, etc). Can load in and act as a 'camera' perfectly fine, however. 

Also autosave complains about not enough drive space, requesting 15MB when I have ~200GB free on that drive.

Memory dump: https://drive.google.com/file/d/1gwC0nc0W9IR_k4Xe3qTcelVJlLMGgueU/view?usp=sharing

**Comment by tinetik** [comment]
Environment: 0.1.1-alpha

Seeing the same 15MB error despite having plenty of space. Host is NOT crashing by all clients are crashing.

Client actions are not causing crashing for host or client.

**Comment by zuev93** [comment]
Part about client actions has been fixed as part of #65 .

Other parts has not been debuged yet.

**Comment by zuev93** [comment]
@tinetik @Iridum-png could some of you (or others) attach a player.log file after the failure?
Thanks!

**Comment by zuev93** [comment]
Issue is fixed.
Be aware that it is required to start a new game to have fix applied.
