### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by Antonio0447** [zuev93/oni_multiplayer#98]
If I play for let’s say 15-20 minutes it will eventually crash if I view more info it has something to do with steam lobby’s not sure, I’ll try to fix this bug later on.

**Comment by zuev93** [comment]
Could you attach the log file please?

**Comment by Antonio0447** [comment]
> Could you attach the log file please?

Where can the log file be found? I’ve also tried looking for the log file before and I looked in the default directory but it’s not there.

**Comment by Antonio0447** [comment]
> Could you attach the log file please?

Also the client also randomly crashes for the same reason “steam lobby’s” and he has to rejoin.

**Comment by Antonio0447** [comment]
When the client spawns a player the host gets this error:
 NullReferenceException: Object reference not set to an instance of an object

MultiplayerMod.Multiplayer.Commands.Screens.Priorities.SetPersonalPriority.Execute () (at <2d7e209004a448a9b8c5b3d474f33c77>:0)
MultiplayerMod.Multiplayer.Configuration.MultiplayerCoordinator+<>c__DisplayClass12_0.<ClientOnCommandReceived>b__1 () (at <2d7e209004a448a9b8c5b3d474f33c77>:0)
MultiplayerMod.Core.Patch.PatchControl+<>c__DisplayClass1_0.<RunWithDisabledPatches>b__0 () (at <2d7e209004a448a9b8c5b3d474f33c77>:0)
MultiplayerMod.Core.Patch.PatchControl.RunWithDisabledPatches[T] (System.Func`1[TResult] action) (at <2d7e209004a448a9b8c5b3d474f33c77>:0)
MultiplayerMod.Core.Patch.PatchControl.RunWithDisabledPatches (System.Action action) (at <2d7e209004a448a9b8c5b3d474f33c77>:0)
MultiplayerMod.Multiplayer.Configuration.MultiplayerCoordinator.ClientOnCommandReceived (System.Object sender, MultiplayerMod.Network.Events.CommandReceivedEventArgs e) (at <2d7e209004a448a9b8c5b3d474f33c77>:0)
MultiplayerMod.Platform.Steam.Network.SteamClient.ReceiveCommands () (at <2d7e209004a448a9b8c5b3d474f33c77>:0)
MultiplayerMod.Platform.Steam.Network.SteamClient.Tick () (at <2d7e209004a448a9b8c5b3d474f33c77>:0)
MultiplayerMod.Platform.Steam.Network.Components.SteamClientComponent.Update () (at <2d7e209004a448a9b8c5b3d474f33c77>:0)

Build: U46-552078-V. The steam crash is different once i get that error ill provide it.

**Comment by Antonio0447** [comment]
[Client Crash-2.txt](https://github.com/zuev93/oni_multiplayer/files/11710633/Client.Crash-2.txt)
[Client Crash-1.txt](https://github.com/zuev93/oni_multiplayer/files/11710634/Client.Crash-1.txt)
here are the client crashes -1 was random and -2 was when joining.

**Comment by Antonio0447** [comment]
> Could you attach the log file please?

Turns out the client kept spawning players which caused the host to crash but the files I’ve attached earlier are real client crashes.
